In [7]:
import sys
from pathlib import Path
import numpy as np

ML_ROOT = Path.cwd().parent
if str(ML_ROOT) not in sys.path:
    sys.path.append(str(ML_ROOT))

print(ML_ROOT)

c:\Abhiram\Projects\ecg-cardiac-abnormality-detection\ml


In [8]:
from src.datasets.dataset_builder import build_dataset
from src.config.constants import MITBIH_RECORDS

X, y, patient_ids = build_dataset(MITBIH_RECORDS)

Processing record 100...
Processing record 101...
Processing record 102...
Processing record 103...
Processing record 104...
Processing record 105...
Processing record 106...
Processing record 107...
Processing record 108...
Processing record 109...
Processing record 111...
Processing record 112...
Processing record 113...
Processing record 114...
Processing record 115...
Processing record 116...
Processing record 117...
Processing record 118...
Processing record 119...
Processing record 121...
Processing record 122...
Processing record 123...
Processing record 124...
Processing record 200...
Processing record 201...
Processing record 202...
Processing record 203...
Processing record 205...
Processing record 207...
Processing record 208...
Processing record 209...
Processing record 210...
Processing record 212...
Processing record 213...
Processing record 214...
Processing record 215...
Processing record 217...
Processing record 219...
Processing record 220...
Processing record 221...


In [9]:
from src.preprocessing.pipeline import prepare_datasets

(
    X_train,
    y_train,
    train_patient_ids,
    X_val,
    y_val,
    val_patient_ids,
    X_test,
    y_test,
    test_patient_ids,
) = prepare_datasets(
    X,
    y,
    patient_ids
)

In [10]:
print(X_train.shape)
print(y_train.shape)
print(train_patient_ids.shape)

print()

print(X_val.shape)
print(y_val.shape)
print(val_patient_ids.shape)

print()

print(X_test.shape)
print(y_test.shape)
print(test_patient_ids.shape)

(74044, 250)
(74044,)
(74044,)

(15440, 250)
(15440,)
(15440,)

(10538, 250)
(10538,)
(10538,)


In [11]:
print(np.unique(y_train))
print(np.unique(y_val))
print(np.unique(y_test))

[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]


In [12]:
print(X_train[0].mean())
print(X_train[0].std())

print(X_val[0].mean())
print(X_val[0].std())

print(X_test[0].mean())
print(X_test[0].std())

-1.1368683772161603e-16
0.9999999503956991
1.4210854715202004e-16
0.9999999655378503
-5.684341886080802e-17
0.9999999447134106


In [13]:
print(
    len(
        set(train_patient_ids)
        &
        set(val_patient_ids)
    )
)

print(
    len(
        set(train_patient_ids)
        &
        set(test_patient_ids)
    )
)

print(
    len(
        set(val_patient_ids)
        &
        set(test_patient_ids)
    )
)

0
0
0


In [14]:
import pandas as pd

print(pd.Series(y_train).value_counts())
print()
print(pd.Series(y_val).value_counts())
print()
print(pd.Series(y_test).value_counts())

0    57922
2     5251
3     4492
4     4387
1     1992
Name: count, dtype: int64

0    10792
2     1603
3     1457
4     1338
1      250
Name: count, dtype: int64

0    6306
3    2123
4    1530
1     304
2     275
Name: count, dtype: int64
